Feat/products
felinto-dev/luqezman-graphql-with-nestjs-mentorship pull request #5
Opened 2020-09-29 21:07 UTC by felinto-dev

- (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/dcc6f11578f9a81583592f15a9b4024e9eae00ad) Add new products module
    - ✔️ (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/commit/ee5a0ad3f86ee8a6063c79afc8bdcaf2c3c299ba#diff-96a20d758e030b096d5569de349503fa568238e0ab514be78826ed9c9f445625) Add GraphQL resolver to get all products
- (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/b2d84f3b5d057969e8434ce4132778f4a19e49c5) Add support for MongoDB
- (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/2090cfbe7a7fa698dd843330cb805d95b1d4bd1a) Fix hot reload bug in Windows

---
Tests
- (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/4d5d7cca74b2f2ec661c7d77cff2cae1af3b2f3c) Add support for Faker
- Mock:
    - (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/commit/445716b8f3fcf22201304ad3e00dfd91887e9cd2#diff-0f7e5149b9128fd66ac39a18d4f2b58867411b5315b4ef12a091224c5b09cd02) Products Service
    - (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/commit/9d12542a91c95bf992bb8d8cc5fafc2a603e323d#diff-20921bb110fc0673ac844631e8df1dacf69083b6d103cd38a28a5696aa7fe9e4) Products Repository
    - (https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/commit/05ca469dca99d4eda022c69b1a7ae3ef1043b0e8#diff-dfd6cb6eb4535cf7c1f3825b32a39efe4d81edf23b49e74ba8e6f9dbd812776b) Product

2020-10-08 13:55 UTC, luqezman requested changes

2020-10-08 13:55 UTC, luqezman commented on src/app.module.ts
> +import { ProductsModule } from './products/products.module';
Why u call "Products" in plural for Product and DbConfig you use in singular?

2020-10-08 13:55 UTC, luqezman commented on src/products/interfaces/product-type.enum.ts
> +  PLUGIN = 'PLUGIN',
why values are in caps?

2020-10-08 13:55 UTC, luqezman commented on src/products/products.resolver.ts
> +import { Resolver, Query } from '@nestjs/graphql';
Sort import keywords

2020-10-08 13:55 UTC, luqezman commented on src/products/products.resolver.ts
> +    private readonly productsService: ProductsService
Where is the interface to high level modules? Can you apply DIP(Dependency inversion principle) here?

2020-10-08 13:55 UTC, luqezman commented on src/products/products.service.ts
> +import { Model } from 'mongoose';
Fix import path order

2020-10-08 13:55 UTC, luqezman commented on src/products/products.service.ts
> +  constructor(@InjectModel(Product.name) private productModel: Model<ProductDocument>) { }
Remove extra space inside brackets

2020-10-08 13:55 UTC, luqezman commented on src/products/products.service.ts
> +  constructor(@InjectModel(Product.name) private productModel: Model<ProductDocument>) { }
add `readonly` to productModel

2020-10-08 13:55 UTC, luqezman commented on src/products/schemas/product.schema.ts
> +  @Prop({ required: true, type: Types.ObjectId, ref: 'Developer' })
I suggest you changing the order to "type, relations, others", in this case:

`{ type: Types.ObjectId, ref: 'Developer', required: true }`

2020-10-08 13:55 UTC, luqezman commented on src/products/schemas/product.schema.ts
> +  @Prop({ required: true, unique: true })
I suggestou changing the order to `{ unique: true, required: true }` since `unique` is more relavant then `required`

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/mocks/mock-product.ts
> +import { ProductType } from "../../interfaces/product-type.enum";
change to single quotes

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/mocks/mock-product.ts
> +    installationInstructions: '',
you can remove this

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/mocks/mock-product.ts
> +    developer: {
change to single line

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/mocks/mock-product.ts
> +    developer: {
change to single line

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
I suggest you using SUT

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +      expect(service).resolves.toBe(mockProductsList)
add ; to the end of line

2020-10-08 13:55 UTC, luqezman commented on src/products/tests/products.service.spec.ts
> +      const products = service.findAllProducts()
is this line really necessary?

2020-10-08 13:55 UTC, luqezman commented on src/app.module.ts
>    providers: [AppService],
why `,` is at the end of line?

2020-10-08 13:55 UTC, luqezman commented on src/products/products.module.ts
> +  providers: [ProductsService, ProductsResolver]
why `,` is not present at the end of line?

2020-10-12 18:52 UTC, felinto-dev commented on src/app.module.ts
> +import { ProductsModule } from './products/products.module';
I think that "db configs" sounds weird. You can read more about it here: https://github.com/nestjs/docs.nestjs.com/issues/1176

2020-10-12 18:57 UTC, felinto-dev commented on src/app.module.ts
>    controllers: [AppController],
Sure. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/713311547269bbae373e661f58810ec7347858f2

2020-10-12 22:32 UTC, felinto-dev commented on src/config/db/db.config.ts
> +  url: process.env.DB_URL
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/e2f2e875d75066521fd6f0a4ed2f3cdff2db9064

2020-10-12 22:34 UTC, felinto-dev commented on src/products/interfaces/product-type.enum.ts
> +  PLUGIN = 'PLUGIN',
Good question. https://stackoverflow.com/questions/3069743/coding-conventions-naming-enums

2020-10-12 22:35 UTC, felinto-dev commented on src/products/products.resolver.ts
> +import { Resolver, Query } from '@nestjs/graphql';
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/1a43e64ed7e0903ff833d388339aff48b22654ee

2020-10-12 22:38 UTC, felinto-dev commented on src/products/tests/mocks/mock-product.ts
> +    developer: {
I don't understand. Putting all of this on a single line separated by a comma decreases readability. It makes no sense to treat a javascript file, like a CSV file.

2020-10-12 22:40 UTC, felinto-dev commented on src/products/tests/products.service.spec.ts
> +      const products = service.findAllProducts()
Of course. Explicit is better than implicit. I prefer this away.

2020-10-12 22:40 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +      const service = resolver.products()
Of course. Explicit is better than implicit. I prefer this way.

2020-10-12 22:48 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
I think that it's a good idea, but I'm using the official NestJS recommendation for tests:
https://github.com/jmcdo29/testing-nestjs/blob/master/apps/graphql-sample/src/cat/cat.resolver.spec.ts
Create a "makeSut", or something like it:
```
const makeSut = (): BcryptAdapter => {
  return new BcryptAdapter(salt)
}
```
https://github.com/rmanguinho/clean-ts-api/blob/master/src/infra/criptography/bcrypt-adapter/bcrypt-adapter.spec.ts

It does not help much in the readability of the code.

https://docs.nestjs.com/fundamentals/testing

2020-10-12 23:26 UTC, luqezman commented on src/products/interfaces/product-type.enum.ts
> +  PLUGIN = 'PLUGIN',
I agree with key in CAPS but value can be in lower.

2020-10-12 23:31 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +      const service = resolver.products()
I mean, the correct variable for this should be "products" instead of "service"

2020-10-12 23:33 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +      const service = resolver.products()
```ts
const products = resolver.products();
expect(service).resolves.toBe(mockProductsList);
```

2020-10-12 23:34 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
You can create the SUT around this. Look to my example: https://github.com/luqezman/todo-graphql-nestjs/blob/master/src/services/todo/todo.service.spec.ts

2020-10-12 23:39 UTC, luqezman commented on src/products/tests/products.service.spec.ts
> +    it('should find all elements from database', async () => {
I suggest you renaming the test name to "should get an array of Product"

2020-10-12 23:39 UTC, luqezman commented on src/products/tests/products.service.spec.ts
> +
Remove that line since you do not like sections

2020-10-12 23:40 UTC, luqezman commented on src/products/tests/products.service.spec.ts
> +      return {
remove return

2020-10-12 23:40 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +      imports: [],
Remove imports

2020-10-12 23:41 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +          useValue: {}
Why useValue is empty?

2020-10-12 23:46 UTC, luqezman commented on src/products/tests/products.resolver.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
Since you are mocking service, you can use jest automock `jest.mock('@/products/products.service');`

2020-10-13 01:43 UTC, luqezman commented on src/config/db/db-config.module.ts
> +        uri: ConfigService.get('db.url'),
the object name is `uri`, the config is "url". Can you fix it?

2020-10-13 01:44 UTC, luqezman commented on src/config/db/db-config.module.ts
>  import configuration from './db.config';
I suggest you changing to dbConfig

2020-10-13 01:45 UTC, luqezman commented on src/products/schemas/product.schema.ts
> +export type ProductDocument = Product & Document;
I suggest you chaing any types/interfaces into a separated folder with these rules

2020-10-13 01:50 UTC, luqezman commented on src/products/tests/mocks/mock-product.ts
> +export const mockProductsList: Product[] = [
can you create mocks using Fakerjs?

2020-10-14 21:28 UTC, felinto-dev commented on src/products/interfaces/product-type.enum.ts
> +  PLUGIN = 'PLUGIN',
Could you provide some links that talk more about this pattern?

2020-10-14 21:45 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +    const module: TestingModule = await Test.createTestingModule({
@luqezman, I understand your point about using SUT as a standard that all developers should understand, on the other hand, NestJS also has its own standard, and as long as it doesn't hurt good clean code principles, NestJS standards should prevail, especially if they result in a leaner and cleaner code.

If I use sut, I will need probably do something like it in each test:
const { sut, todoRepository } = await makeSut();

> Since you are mocking service, you can use jest automock jest.mock('@/products/products.service');

I do not want to mock a specific function from the repository for each test, EXCEPT, in case of error. By default, you mock all success cases and only mock the error case in the tests.

https://github.com/angelogluz/nest-angelo-youtube/blob/master/src/users/user.service.spec.ts

You may not realize it but it will always result in a leaner code, with LESS REPETITION.

2020-10-14 21:48 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +      const service = resolver.products()
Sure. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/e1aff0faf57b0a1a676232815a5ea3f1b94859f3

2020-10-14 21:49 UTC, felinto-dev commented on src/products/tests/products.service.spec.ts
> +    it('should find all elements from database', async () => {
Sounds better. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/61a5e46041fde35b67f1a3db76a60e32536754f2

2020-10-14 21:50 UTC, felinto-dev commented on src/products/tests/products.service.spec.ts
> +      return {
I did it but I don't have the commit ID. You could check the project files? Sorry about it.

2020-10-14 21:52 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +      imports: [],
Sure. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/04691640273ae79032523b8f3eddcb8009eba24b

2020-10-15 19:18 UTC, felinto-dev commented on src/products/interfaces/product-type.enum.ts
> +  PLUGIN = 'PLUGIN',
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/b8650cf6fa6195d9af5d1489b481e8ad51f2b520

2020-10-15 19:27 UTC, felinto-dev commented on src/config/db/db-config.module.ts
> +        uri: ConfigService.get('db.url'),
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/fba86001155b351bd23f79fde490b794f6bb26ae

2020-10-15 19:29 UTC, felinto-dev commented on src/config/db/db-config.module.ts
>  import configuration from './db.config';
I'm not sure if I understand. Could you check? https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/d084cf2cd77b91addf20cd7413feb2c859b17565

2020-10-21 12:38 UTC, felinto-dev commented on src/products/tests/mocks/mock-product.ts
> +export const mockProductsList: Product[] = [
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/4d5d7cca74b2f2ec661c7d77cff2cae1af3b2f3c

2020-10-21 13:54 UTC, felinto-dev commented on src/products/products.service.ts
> +  constructor(@InjectModel(Product.name) private productModel: Model<ProductDocument>) { }
Sure. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/d1f83c6cf52c03517523fe8a62066374a753fe18

2020-10-21 13:55 UTC, felinto-dev commented on src/products/schemas/product.schema.ts
> +  @Prop({ required: true, type: Types.ObjectId, ref: 'Developer' })
I solved it in another way. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/7cffae6c0ec5d4c54029f07032d1226d2ff37ccd

2020-10-21 13:57 UTC, felinto-dev commented on src/products/schemas/product.schema.ts
> +  @Prop({ required: true, unique: true })
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/pull/5/commits/ece91c40ce28404a6b6887f0828e8da79e3bb621

2020-10-22 19:35 UTC, felinto-dev commented on src/products/schemas/developer.schema.ts
> +  installationInstructions?: string;
I understand your point, but this is is not a valid way to apply KISS, the same way you have trouble applying YAGNI, LESS CODE, etc. I think that you should review these concepts.

In the frontend website I will show for the final user the name "installationInstructions", so doesn't make sense to have a different name in the backend and another name in frontend. This will generate confusion and _misleading information_, and if a code generates misleading information, no matter what design pattern the code use, **will be always a bad code**.

2020-10-22 19:36 UTC, felinto-dev commented on src/products/tests/products.resolver.spec.ts
> +          useValue: {}
Solved. https://github.com/felinto-dev/luqezman-graphql-with-nestjs-mentorship/commit/ab672b93527367c96ff6646046501f2f0d1a2668#diff-372f5a6f065f1e59a0328d57ba75a7da6b80e303ce5ab97cb7e142756e3acdef

2020-10-30 16:39 UTC, luqezman approved these changes

2020-10-30 16:39 UTC, merged

2020-10-30 16:40 UTC, luqezman commented
Looks good for me, rdy4merge